import MainContentWrapper from "@/components/template/MainContentWrapper/MainContentWrapper";
import { NFTRollingBanner } from "@/components/staking/NFTRollingBanner";
import "@/css/benefits.css";

function Benefits() {
  const benefits = [
    {
      icon: "/benefits_icon/money-tree.png",
      title: "HoneyPot Finance POL Vault Rewards",
      description: "Earn automatic yields from the Protocol-Owned Liquidity vault. Your NFT entitles you to a share of the vault's performance, generating passive income from DeFi strategies across multiple chains."
    },
    {
      icon: "/benefits_icon/charging-honey-token.png",
      title: "HPOT Token Airdrop",
      description: "Receive exclusive HPOT token airdrops reserved for NFT holders. Be rewarded for your early support and loyalty to the HoneyPot Finance ecosystem with governance tokens."
    },
    {
      icon: "/benefits_icon/chain.png",
      title: "Perpetual DEX Revenue Sharing",
      description: "Share in the trading fees generated by the HoneyPot perpetual exchange. As trading volume grows, so does your share of the revenue - a true stake in the protocol's success."
    },
    {
      icon: "/benefits_icon/rocket.png",
      title: "Enhanced Staking Rewards",
      description: "Lock your NFT to supercharge your earnings with time-based multipliers. The longer you stake, the higher your rewards - reaching up to 3x+ after just 60 days!"
    },
    {
      icon: "/benefits_icon/shield.png",
      title: "Ecosystem Access & Benefits",
      description: "Enjoy priority access to new features, exclusive community events, governance voting rights, and special privileges across the entire HoneyPot Finance ecosystem."
    }
  ];

  return (
    <div className="App benefits">
      <MainContentWrapper>
        {/* NFT Rolling Banner - Full Width */}
        <NFTRollingBanner />

        <main className="benefits-main">
          <h1 className="benefits-title">NFT Holder Benefits</h1>
          <p className="benefits-subtitle">
            Unlock exclusive rewards and revenue streams by holding HoneyGenesis NFTs
          </p>

          {/* Benefits Grid */}
          <div className="benefits-grid">
            {benefits.map((benefit, index) => (
              <div key={index} className="benefit-card">
                <div className="benefit-icon">
                  <img src={benefit.icon} alt={benefit.title} />
                </div>
                <h3 className="benefit-title">{benefit.title}</h3>
                <p className="benefit-description">{benefit.description}</p>
              </div>
            ))}
          </div>
        </main>
      </MainContentWrapper>
    </div>
  );
}

export default Benefits;
