import MainContentWrapper from "@/components/template/MainContentWrapper/MainContentWrapper";
import { NFTRollingBanner } from "@/components/staking/NFTRollingBanner";
import "@/css/staking.css";

function Benefits() {
  return (
    <div className="App staking">
      <MainContentWrapper>
        <main className="main">
          <h1 className="title">NFT Holder Benefits 💎</h1>

          <div
            className="staking-connect-prompt"
            style={{ marginBottom: "2rem" }}
          >
            <p
              className="desc"
              style={{ fontSize: "1.1rem" }}
            >
              Unlock exclusive rewards and revenue streams by holding
              HoneyGenesis NFTs
            </p>
          </div>

          {/* NFT Rolling Banner */}
          <NFTRollingBanner />

          {/* All Benefits */}
          <div
            className="staking-tabs-container"
            style={{ marginBottom: "2rem" }}
          >
            <div className="staking-tab-content">
              <div
                style={{
                  display: "grid",
                  gridTemplateColumns:
                    "repeat(auto-fit, minmax(min(300px, 100%), 1fr))",
                  gap: "1.5rem",
                }}
              >
                <div className="benefit-card">
                  <div className="benefit-icon">🏦</div>
                  <h3>HoneyPot Finance POL Vault Rewards</h3>
                  <p>
                    Earn automatic yields from the Protocol-Owned Liquidity
                    vault. Your NFT entitles you to a share of the vault's
                    performance, generating passive income from DeFi strategies
                    across multiple chains.
                  </p>
                </div>
                <div className="benefit-card">
                  <div className="benefit-icon">🪂</div>
                  <h3>HPOT Token Airdrop</h3>
                  <p>
                    Receive exclusive HPOT token airdrops reserved for NFT
                    holders. Be rewarded for your early support and loyalty to
                    the HoneyPot Finance ecosystem with governance tokens.
                  </p>
                </div>
                <div className="benefit-card">
                  <div className="benefit-icon">📊</div>
                  <h3>Perpetual DEX Revenue Sharing</h3>
                  <p>
                    Share in the trading fees generated by the HoneyPot
                    perpetual exchange. As trading volume grows, so does your
                    share of the revenue - a true stake in the protocol's
                    success.
                  </p>
                </div>
                <div className="benefit-card">
                  <div className="benefit-icon">💰</div>
                  <h3>Enhanced Staking Rewards</h3>
                  <p>
                    Lock your NFT to supercharge your earnings with time-based
                    multipliers. The longer you stake, the higher your rewards -
                    reaching up to 3x+ after just 60 days!
                  </p>
                </div>
                <div className="benefit-card">
                  <div className="benefit-icon">🌟</div>
                  <h3>Ecosystem Access & Benefits</h3>
                  <p>
                    Enjoy priority access to new features, exclusive community
                    events, governance voting rights, and special privileges
                    across the entire HoneyPot Finance ecosystem.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </main>
      </MainContentWrapper>
    </div>
  );
}

export default Benefits;
